name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main
      # Run action when pushing to the main branch
    paths:
      - 'worker.js'
      - 'wrangler.toml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3

      - name: Publish to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        env:
          # This pulls the IMGBB API key from your GitHub secrets and injects it securely
          IMGBB_API_KEY: ${{ secrets.IMGBB_API_KEY }}